### ISSUE TITLE
"Show Total Cash held" Denomination enhancement

### ISSUE THREAD

**Issue by akshayh696** [piyushjain2/confmgmt-ca#3]
Description:
The quantity of each denomination should be displayed and the amounts can be tallied with "Total Cash Held" and "Total Coins Held"

Acceptance Requirement Steps:

1. Log into Maintenance System
2. Press "Show Total Cash Held"
3. Specific quantities of currency by denomination are displayed
4. Press "Collect Cash"
5. Compare amount with individual denomination. The number of coins and currency can be tallied with dispensed number
6. Log-Out
7. Upon successful logout, the affected fields should be reset to null

**Comment by manhpd** [comment]
Hi all, I have done the Analysist for this change request. Here is the list of the modules affected:

1. Store Module
CoinDisplay.java
CoinLabelItem.java
CoinLabelItemDisplay.java
StoreController.java

2. Maintenance Module
MaintenanceController.java
MaintenancePanel.java
TotalCashButtonListener.java

@akshayh696 kindly review the changes

**Comment by akshayh696** [comment]
Hi @piyushjain2 ,

Can you create a separate branch for this enhancement. Also @nhatdx, would be taking care of the development.

**Comment by piyushjain2** [comment]
Hi @Pratyush2703 ,

@nhatdx has done the changes and I have reviewed them from the technical side. Kindly proceed with your testing

**Comment by Pratyush2703** [comment]
The issue was tested using the reproduction procedure and the enhancement has been effected. The quantity of each denomination is be displayed and the amounts can be tallied with "Total Cash Held" and "Total Coins Held"

The issue can now be closed

![image](https://user-images.githubusercontent.com/36813309/45641810-178c0a00-bae9-11e8-8972-54906fa961f7.png)
![image](https://user-images.githubusercontent.com/36813309/45641821-1fe44500-bae9-11e8-81d8-999d4418ea91.png)
![image](https://user-images.githubusercontent.com/36813309/45641826-270b5300-bae9-11e8-9087-96ffccd03fae.png)
![image](https://user-images.githubusercontent.com/36813309/45641835-2d99ca80-bae9-11e8-8bf3-82c6150fbbcf.png)
